/**
 * AI Feature Types for Solom
 * 
 * These types define the structure for AI-powered features including:
 * - Financial Assistant
 * - Sentiment Analysis
 * - Smart Alerts
 * - Portfolio Analysis
 * - Predictions
 */

// ============================================
// Core Types
// ============================================

/**
 * User context for AI interactions
 */
export interface AIContext {
  /** User's watchlist symbols */
  watchlist: string[];
  /** User's portfolio if available */
  portfolio?: Portfolio;
  /** Risk tolerance level */
  riskTolerance: RiskTolerance;
  /** Investment goals */
  investmentGoals: InvestmentGoal[];
  /** Preferred analysis depth */
  analysisDepth: 'quick' | 'standard' | 'deep';
}

export type RiskTolerance = 'conservative' | 'moderate' | 'aggressive';

export interface InvestmentGoal {
  type: 'growth' | 'income' | 'preservation' | 'speculation';
  timeframe: 'short' | 'medium' | 'long';
  targetReturn?: number;
}

export interface Portfolio {
  holdings: Holding[];
  totalValue: number;
  currency: string;
}

export interface Holding {
  symbol: string;
  shares: number;
  averageCost: number;
  currentPrice: number;
  marketValue: number;
  gain: number;
  gainPercent: number;
}

// ============================================
// Financial Assistant Types
// ============================================

/**
 * Request to the financial assistant
 */
export interface AssistantRequest {
  /** User's query in natural language */
  query: string;
  /** Conversation history for context */
  conversationHistory?: AssistantMessage[];
  /** User context */
  context: AIContext;
  /** Requested response format */
  format?: 'text' | 'structured' | 'both';
}

/**
 * Message in the conversation
 */
export interface AssistantMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  /** Structured data if any */
  data?: AssistantStructuredData;
  /** Sources cited in the response */
  sources?: Source[];
}

export interface Source {
  type: 'news' | 'filing' | 'data' | 'analysis';
  title: string;
  url?: string;
  timestamp: Date;
}

/**
 * Structured data that can accompany a response
 */
export type AssistantStructuredData = 
  | StockRecommendation
  | PriceAnalysis
  | CompanyOverview
  | ComparisonData
  | ScreenResults;

export interface StockRecommendation {
  type: 'recommendation';
  symbol: string;
  action: 'buy' | 'sell' | 'hold' | 'watch';
  confidence: number;
  reasoning: string[];
  priceTarget?: number;
  stopLoss?: number;
  riskLevel: 'low' | 'medium' | 'high';
}

export interface PriceAnalysis {
  type: 'price_analysis';
  symbol: string;
  currentPrice: number;
  support: number[];
  resistance: number[];
  trend: 'bullish' | 'bearish' | 'neutral';
  indicators: TechnicalIndicator[];
}

export interface TechnicalIndicator {
  name: string;
  value: number | string;
  signal: 'bullish' | 'bearish' | 'neutral';
  description: string;
}

export interface CompanyOverview {
  type: 'company_overview';
  symbol: string;
  name: string;
  sector: string;
  industry: string;
  marketCap: number;
  description: string;
  keyMetrics: Record<string, number | string>;
  recentNews: NewsItem[];
}

export interface NewsItem {
  title: string;
  source: string;
  timestamp: Date;
  sentiment?: number;
  url?: string;
}

export interface ComparisonData {
  type: 'comparison';
  symbols: string[];
  metrics: Record<string, Record<string, number | string>>;
  winner?: string;
  analysis: string;
}

export interface ScreenResults {
  type: 'screen_results';
  query: string;
  results: ScreenResult[];
  totalMatches: number;
  executionTime: number;
}

export interface ScreenResult {
  symbol: string;
  name: string;
  price: number;
  change: number;
  changePercent: number;
  matchReasons: string[];
}

/**
 * Response from the financial assistant
 */
export interface AssistantResponse {
  /** The assistant's message */
  message: AssistantMessage;
  /** Whether the response was generated by Council Mode */
  councilMode?: boolean;
  /** Agents involved if Council Mode was used */
  agents?: CouncilAgent[];
  /** Time taken to generate response */
  latency: number;
  /** Model used */
  model: string;
}

export interface CouncilAgent {
  name: string;
  role: string;
  contribution: string;
  confidence: number;
}

// ============================================
// Sentiment Analysis Types
// ============================================

/**
 * Sentiment analysis result for a symbol
 */
export interface SentimentScore {
  symbol: string;
  /** Overall sentiment score (-1 to 1) */
  overall: number;
  /** Sentiment from news sources */
  news: number;
  /** Sentiment from social media */
  social: number;
  /** Sentiment from analyst ratings */
  analyst: number;
  /** Trend direction */
  trend: SentimentTrend;
  /** Key topics mentioned */
  keyTopics: string[];
  /** When the analysis was performed */
  analyzedAt: Date;
  /** Data freshness */
  dataPoints: number;
}

export type SentimentTrend = 'improving' | 'declining' | 'stable' | 'volatile';

/**
 * Aggregated sentiment for multiple symbols
 */
export interface MarketSentiment {
  overall: number;
  bySector: Record<string, number>;
  topGainers: SentimentScore[];
  topLosers: SentimentScore[];
  timestamp: Date;
}

/**
 * Sentiment alert configuration
 */
export interface SentimentAlertConfig {
  symbol: string;
  threshold: number;
  direction: 'above' | 'below' | 'change';
  notificationMethod: ('email' | 'push' | 'sms')[];
  enabled: boolean;
}

// ============================================
// Smart Alerts Types
// ============================================

/**
 * Types of smart alerts
 */
export type AlertType = 
  | 'breakout'
  | 'breakdown'
  | 'volume_spike'
  | 'earnings_near'
  | 'unusual_activity'
  | 'sentiment_shift'
  | 'price_target'
  | 'stop_loss'
  | 'dividend_near'
  | 'ipo_near';

/**
 * Smart alert generated by AI
 */
export interface SmartAlert {
  id: string;
  symbol: string;
  type: AlertType;
  /** Confidence level (0-1) */
  confidence: number;
  /** AI-generated explanation */
  reasoning: string;
  /** Suggested action for the user */
  suggestedAction: string;
  /** Related data */
  data?: Record<string, unknown>;
  /** When the alert was generated */
  createdAt: Date;
  /** Whether the alert has been acknowledged */
  acknowledged: boolean;
  /** Priority level */
  priority: AlertPriority;
}

export type AlertPriority = 'low' | 'medium' | 'high' | 'urgent';

/**
 * Alert with additional context
 */
export interface EnrichedAlert extends SmartAlert {
  /** Current price when alert was generated */
  priceAtAlert: number;
  /** Price movement since alert */
  priceMovement?: number;
  /** Whether the alert prediction was accurate */
  outcome?: 'accurate' | 'inaccurate' | 'pending';
  /** Historical accuracy for this alert type */
  historicalAccuracy?: number;
}

/**
 * Alert preferences for a user
 */
export interface AlertPreferences {
  /** Total alerts per day limit */
  dailyLimit: number;
  /** Minimum confidence to trigger alert */
  minConfidence: number;
  /** Preferred alert types */
  enabledTypes: AlertType[];
  /** Quiet hours */
  quietHours?: {
    start: string; // HH:mm
    end: string; // HH:mm
    timezone: string;
  };
  /** Symbols to watch (empty = all watchlist) */
  symbols: string[];
}

// ============================================
// Portfolio Analysis Types
// ============================================

/**
 * Complete portfolio analysis result
 */
export interface PortfolioAnalysis {
  /** Overall diversification score (0-100) */
  diversificationScore: number;
  /** Overall risk level */
  riskLevel: RiskTolerance;
  /** Concentration by sector */
  sectorExposure: Record<string, number>;
  /** Concentration by geography */
  geographicExposure: Record<string, number>;
  /** Asset class distribution */
  assetClassExposure: Record<string, number>;
  /** Correlation matrix for holdings */
  correlations: CorrelationPair[];
  /** AI-generated suggestions */
  suggestions: PortfolioSuggestion[];
  /** Stress test results */
  stressTests: StressTestResult[];
  /** Analysis timestamp */
  analyzedAt: Date;
}

export interface CorrelationPair {
  pair: [string, string];
  correlation: number; // -1 to 1
  risk: 'diversifying' | 'neutral' | 'concentrating';
}

export interface PortfolioSuggestion {
  id: string;
  type: SuggestionType;
  priority: 'low' | 'medium' | 'high';
  title: string;
  description: string;
  impact: string;
  actions: SuggestedAction[];
}

export type SuggestionType = 
  | 'diversification'
  | 'risk_reduction'
  | 'tax_optimization'
  | 'rebalancing'
  | 'opportunity';

export interface SuggestedAction {
  type: 'buy' | 'sell' | 'hold' | 'research';
  symbol?: string;
  amount?: number;
  reason: string;
}

export interface StressTestResult {
  scenario: string;
  description: string;
  portfolioImpact: number; // percent change
  worstCase?: number;
  bestCase?: number;
  recommendations: string[];
}

// ============================================
// Predictions Types
// ============================================

/**
 * Price prediction result
 */
export interface PricePrediction {
  symbol: string;
  /** Prediction timeframe */
  timeframe: PredictionTimeframe;
  /** Predicted direction */
  direction: 'up' | 'down' | 'neutral';
  /** Confidence level (0-1) */
  confidence: number;
  /** Predicted target price */
  targetPrice?: number;
  /** Current price at prediction time */
  currentPrice: number;
  /** Key factors influencing prediction */
  keyFactors: PredictionFactor[];
  /** Historical model accuracy */
  modelAccuracy?: number;
  /** When the prediction was made */
  predictedAt: Date;
}

export type PredictionTimeframe = '1d' | '3d' | '1w' | '2w' | '1m' | '3m';

export interface PredictionFactor {
  name: string;
  impact: 'positive' | 'negative' | 'neutral';
  weight: number;
  description: string;
}

/**
 * Prediction model metadata
 */
export interface PredictionModel {
  id: string;
  name: string;
  type: 'classification' | 'regression' | 'ensemble';
  accuracy: number;
  precision: number;
  recall: number;
  lastTrained: Date;
  features: string[];
}

// ============================================
// AI Configuration Types
// ============================================

/**
 * Configuration for AI features
 */
export interface AIConfig {
  /** Default model to use */
  defaultModel: string;
  /** Enable Council Mode for complex queries */
  councilMode: boolean;
  /** Enable System 2 reasoning */
  system2Reasoning: boolean;
  /** Max tokens for responses */
  maxTokens: number;
  /** Temperature for generation */
  temperature: number;
  /** Enable sentiment analysis */
  sentimentEnabled: boolean;
  /** Enable smart alerts */
  alertsEnabled: boolean;
  /** Enable predictions */
  predictionsEnabled: boolean;
}

/**
 * Default AI configuration
 */
export const DEFAULT_AI_CONFIG: AIConfig = {
  defaultModel: 'ollama/glm-5:cloud',
  councilMode: true,
  system2Reasoning: false,
  maxTokens: 4096,
  temperature: 0.7,
  sentimentEnabled: true,
  alertsEnabled: true,
  predictionsEnabled: false,
};

// ============================================
// API Response Types
// ============================================

/**
 * Standard API response wrapper
 */
export interface AIResponse<T> {
  success: boolean;
  data?: T;
  error?: AIError;
  metadata?: {
    model: string;
    latency: number;
    tokensUsed?: number;
  };
}

export interface AIError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

// ============================================
// Utility Types
// ============================================

/**
 * Async result with loading states
 */
export type AsyncResult<T, E = Error> = 
  | { status: 'idle' }
  | { status: 'loading' }
  | { status: 'success'; data: T }
  | { status: 'error'; error: E };